# Generated by Django 5.1.4 on 2025-01-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='slug',
        ),
        migrations.AddField(
            model_name='teachers',
            name='Email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='head_of',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
