# Generated by Django 5.1.4 on 2025-01-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_teachers_phone_number_remove_teachers_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='head_of',
            new_name='position',
        ),
    ]
