# Generated by Django 5.1.4 on 2025-01-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_head_of_teachers_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='class_teacher_of',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
