# Generated by Django 5.1.4 on 2025-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teachers_class_teacher_of_teachers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='class_teacher_of',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
