# Generated by Django 5.1.4 on 2025-01-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='full_name',
            new_name='name',
        ),
    ]
