# Generated by Django 5.1.4 on 2025-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_full_name_feedback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('contact_no', models.IntegerField(null=True)),
                ('parents_names', models.CharField(max_length=200)),
                ('blood_gr', models.CharField(max_length=10)),
                ('emergency', models.IntegerField(null=True)),
            ],
        ),
    ]
