# Generated by Django 5.1.4 on 2025-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_names',
            field=models.CharField(max_length=400),
        ),
    ]
