# Generated by Django 5.1.4 on 2025-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_result_percentage_result_total_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_class_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
