# Generated by Django 5.1.4 on 2025-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
