# Generated by Django 5.1.4 on 2025-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_exam_total_time_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
    ]
