# Generated by Django 5.1.4 on 2025-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
