# Generated by Django 5.1.4 on 2025-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_exam_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
