# Generated by Django 5.1.4 on 2025-01-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_exam_end_time_alter_exam_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
